In [6]:
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import ElasticNetCV
from sklearn.metrics import mean_squared_error,r2_score

In [2]:
insurance_data = pd.read_csv("01_insurance.csv")

In [3]:
insurance_data.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [4]:
#Create useful and interacted features
X = insurance_data.drop(columns = ["charges"])
y = insurance_data["charges"]

X = pd.get_dummies(X, columns = ["region", "sex", "smoker"], drop_first = True, dtype = int)
#Creating new features

X["bmi_smoker"] = X["bmi"] * X["smoker_yes"]
X["age_smoker"] = X["age"] * X["smoker_yes"]
X.head()

,age,bmi,children,region_northwest,region_southeast,region_southwest,sex_male,smoker_yes,bmi_smoker,age_smoker
0,19,27.900,0,0,0,1,0,1,27.9,19
1,18,33.770,1,0,1,0,1,0,0.0,0
2,28,33.000,3,0,1,0,1,0,0.0,0
3,33,22.705,0,1,0,0,1,0,0.0,0
4,32,28.880,0,1,0,0,1,0,0.0,0

In [5]:
#Train Test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [10]:
#using ElasticNetCV model
elasticnetcv_model = ElasticNetCV(cv= 5,random_state=42)
elasticnetcv_model.fit(X_train,y_train)
print("Best alpha:",elasticnetcv_model.alpha_)

Best alpha: 312.8429233544063
3479.618928742546

In [12]:
#prediction
y_predict = elasticnetcv_model.predict(X_test)

In [13]:
#r2_score
r2 = r2_score(y_test,y_predict)
print("r2_score:",r2)

r2_score: 0.7189184122635015