In [4]:
import pandas as pd

In [9]:
df = pd.read_csv("globalAirQuality.csv")
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [33]:
#selecting data
#selecting columns
df[["country","aqi"]]

      country  aqi
0          US  108
1          US   90
2          US   84
3          US  158
4          US   97
...       ...  ...
17995      CH  103
17996      CH  105
17997      CH  122
17998      CH   95
17999      CH   88

[18000 rows x 2 columns]

In [32]:
#selecting columns
print(df.loc[0])
print(df.loc[0:2])     #index 2 is included
print(df.iloc[0])
print(df.iloc[0:2])    #index 2 is included

timestamp      2025-11-04 18:25:17.554219
country                                US
city                             New York
latitude                           40.713
longitude                         -74.006
pm25                               50.295
pm10                              108.938
no2                                27.998
so2                                 6.539
o3                                 52.568
co                                  1.096
aqi                                   108
temperature                        18.504
humidity                           70.168
wind_speed                          3.725
Name: 0, dtype: object
                    timestamp country      city  latitude  longitude    pm25  \
0  2025-11-04 18:25:17.554219      US  New York    40.713    -74.006  50.295
1  2025-11-04 19:25:17.554219      US  New York    40.713    -74.006  32.083
2  2025-11-04 20:25:17.554219      US  New York    40.713    -74.006  42.250

      pm10     no2    so2      o3     co  aqi  temperature  humidity  \
0  108.938  27.998  6.539  52.568  1.096  108       18.504    70.168
1   63.043  36.120  4.021  43.536  1.075   90        5.838    80.088
2   82.553  26.935  9.538  23.320  0.977   84       31.833    62.783

   wind_speed
0       3.725
1       8.969
2       9.650
timestamp      2025-11-04 18:25:17.554219
country                                US
city                             New York
latitude                           40.713
longitude                         -74.006
pm25                               50.295
pm10                              108.938
no2                                27.998
so2                                 6.539
o3                                 52.568
co                                  1.096
aqi                                   108
temperature                        18.504
humidity                           70.168
wind_speed                          3.725
Name: 0, dtype: object
                    timestamp country      city  latitude  longitude    pm25  \
0  2025-11-04 18:25:17.554219      US  New York    40.713    -74.006  50.295
1  2025-11-04 19:25:17.554219      US  New York    40.713    -74.006  32.083

      pm10     no2    so2      o3     co  aqi  temperature  humidity  \
0  108.938  27.998  6.539  52.568  1.096  108       18.504    70.168
1   63.043  36.120  4.021  43.536  1.075   90        5.838    80.088

   wind_speed
0       3.725
1       8.969

In [49]:
#selecting rows and columns
print(df.loc[0,"aqi"])
print(df.loc[1:2,["aqi","country"]])
# df.iloc[1:2,["aqi","country"]]        shows error because we only pass index not string in iloc instead we write this
print(df.iloc[1:3,[11,1]])

108
   aqi country
1   90      US
2   84      US
   aqi country
1   90      US
2   84      US

In [52]:
#Selecting single scalar value (at & iat)
print(df.at[0,"city"])
print(df.iat[0,2])

New York
New York