In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("globalAirQuality.csv")

In [5]:
#Filter data
print(df[df["aqi"] > 100])

                        timestamp country      city  latitude  longitude  \
0      2025-11-04 18:25:17.554219      US  New York    40.713    -74.006
3      2025-11-04 21:25:17.554219      US  New York    40.713    -74.006
6      2025-11-05 00:25:17.554219      US  New York    40.713    -74.006
7      2025-11-05 01:25:17.554219      US  New York    40.713    -74.006
8      2025-11-05 02:25:17.554219      US  New York    40.713    -74.006
...                           ...     ...       ...       ...        ...
17991  2025-11-19 09:25:17.554219      CH    Zurich    47.377      8.542
17993  2025-11-19 11:25:17.554219      CH    Zurich    47.377      8.542
17995  2025-11-19 13:25:17.554219      CH    Zurich    47.377      8.542
17996  2025-11-19 14:25:17.554219      CH    Zurich    47.377      8.542
17997  2025-11-19 15:25:17.554219      CH    Zurich    47.377      8.542

         pm25     pm10     no2    so2      o3     co  aqi  temperature  \
0      50.295  108.938  27.998  6.539  52.568  1.096  108       18.504
3      30.403   79.951  63.536  7.609  31.369  0.230  158       23.140
6      77.690   65.198  20.302  7.641  62.687  0.734  155       36.729
7      57.816  111.709  34.533  6.945  41.304  0.771  115       37.891
8      60.914   44.775  40.936  6.779  36.751  1.014  121       24.092
...       ...      ...     ...    ...     ...    ...  ...          ...
17991  52.120   71.160  35.405  7.752  39.811  0.878  104       32.556
17993  76.613   37.495  29.662  5.419  57.042  1.103  153       20.437
17995  27.899   74.179  41.474  6.677  50.869  1.028  103        7.079
17996   2.950   47.988  42.235  2.821  35.551  0.644  105       28.734
17997  61.347   72.908  46.976  5.763  66.492  0.947  122       21.951

       humidity  wind_speed
0        70.168       3.725
3        89.153       8.956
6        47.651       4.542
7        53.314       7.605
8        48.148       8.686
...         ...         ...
17991    31.372       2.787
17993    79.602       2.663
17995    52.443       7.452
17996    85.678       4.496
17997    72.311       9.660

[9721 rows x 15 columns]

In [7]:
df[(df["aqi"] > 100) & (df["city"] == "Zurich")]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
17640,2025-11-04 18:25:17.554219,CH,Zurich,47.377,8.542,37.787,104.854,23.550,11.285,17.016,0.614,104,34.719,46.797,9.232
17642,2025-11-04 20:25:17.554219,CH,Zurich,47.377,8.542,68.172,105.368,19.422,5.672,47.163,0.655,136,16.829,49.257,3.844
17643,2025-11-04 21:25:17.554219,CH,Zurich,47.377,8.542,22.468,126.858,28.478,8.208,41.994,0.756,126,11.519,79.811,1.452
17646,2025-11-05 00:25:17.554219,CH,Zurich,47.377,8.542,49.064,109.248,46.236,9.481,52.182,0.446,115,28.316,89.041,6.218
17647,2025-11-05 01:25:17.554219,CH,Zurich,47.377,8.542,7.972,47.741,66.126,7.945,46.516,0.795,165,9.850,26.160,9.590
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17991,2025-11-19 09:25:17.554219,CH,Zurich,47.377,8.542,52.120,71.160,35.405,7.752,39.811,0.878,104,32.556,31.372,2.787
17993,2025-11-19 11:25:17.554219,CH,Zurich,47.377,8.542,76.613,37.495,29.662,5.419,57.042,1.103,153,20.437,79.602,2.663
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660

In [13]:
aqi_data = df[(df["aqi"] > 100) & (df["city"] == "Zurich")][["aqi","city"]]
print(aqi_data)

       aqi    city
17640  104  Zurich
17642  136  Zurich
17643  126  Zurich
17646  115  Zurich
17647  165  Zurich
...    ...     ...
17991  104  Zurich
17993  153  Zurich
17995  103  Zurich
17996  105  Zurich
17997  122  Zurich

[194 rows x 2 columns]

In [15]:
# aqi_data.loc[0]      error loc[6] is correct
aqi_data.iloc[0]

aqi        104
city    Zurich
Name: 17640, dtype: object

In [29]:
aqi_value = 100
df.query("aqi > @aqi_value & temperature > 30")[["city","aqi"]]

           city  aqi
6      New York  155
7      New York  115
14     New York  121
17     New York  127
25     New York  113
...         ...  ...
17947    Zurich  107
17950    Zurich  140
17975    Zurich  111
17976    Zurich  146
17991    Zurich  104

[2384 rows x 2 columns]