In [1]:
import pandas as pd

In [2]:
df1 = pd.DataFrame({
    "id": [1,2,3],
    "name": ["ubaid","mohsin","sahil"]
})
df2 = pd.DataFrame({
    "id": [4,5,6],
    "name": ["kamran","moien","faheem"]
})

In [3]:
#row wise concationation
pd.concat([df1,df2])

   id    name
0   1   ubaid
1   2  mohsin
2   3   sahil
0   4  kamran
1   5   moien
2   6  faheem

In [5]:
#row wise concationation
pd.concat([df1,df2],axis=1)

   id    name  id    name
0   1   ubaid   4  kamran
1   2  mohsin   5   moien
2   3   sahil   6  faheem